// This class is automatically included in FastlaneRunner during build

// This autogenerated file will be overwritten or replaced during build time, or when you initialize `scan`
//
//  ** NOTE **
//  This file is provided by fastlane and WILL be overwritten in future updates
//  If you want to add extra functionality to this project, create a new file in a
//  new group so that it won't be marked for upgrade
//

class Scanfile: ScanfileProtocol {
    var project:String {return "RadixSDK.xcodeproj"}
    var scheme: String {return "UnitTests"}
    var device: String {return "iPhone 11 Pro"}
    
    var prelaunch_simulator: Bool? {return true}
    var include_simulator_logs: Bool? {return true}
    var clean: Bool? {true}
    var skip_build: Bool? {true}
    var skip_detect_devices: Bool? {true}
    
}

