disabled_rules:
  - nesting
  - trailing_newline
  - trailing_whitespace
  - todo
  - closure_parameter_position
  - unused_closure_parameter
  - mark
  - weak_delegate
  - empty_parameters

included:
  - Source

excluded:
  - Carthage
  - Pods
  - Configurations

line_length: 300
type_name:
  min_length: 
    warning: 3
    error: 2
  max_length:
    warning: 60
    error:  70

file_length:
  warning: 200
  error: 300
  ignore_comment_only_lines: true

identifier_name:
  min_length:
    warning: 3
    error: 2
  max_length:
    warning: 60
    error:  70
  excluded:
    - id
    - to
    - in
    - of
    - by
    - i
    - r
    - s
    - x
    - y

type_body_length:
  - 75 # warning
  - 150 # error

function_parameter_count:
  # Apple's Combine `schedule` takes 5 parameters
  # https://developer.apple.com/documentation/combine/scheduler/3213636-schedule
  # thus seams prudent to accept 5.
  - 6 # warning, 
  - 7 # error

function_body_length:
  - 30 # warning
  - 40 # error

generic_type_name:
  max_length:
    warning: 30
    error:  35

